apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-postgres-exporter
  labels:
    app: {{ .Values.app.label }}-exporter
spec:
  ports:
    - port: 9187
      targetPort: 9187
      name: metrics
  selector:
    app: {{ .Values.app.label }}-exporter
  type: ClusterIP

