apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-postgres-pvc
  labels:
    app: postgres
spec:
  accessModes:
{{ toYaml .Values.postgres.storage.accessModes | indent 4 }}
  resources:
    requests:
      storage: {{ .Values.postgres.storage.size }}
  storageClassName: {{ .Values.postgres.storage.className | quote }}
