apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.postgres.secretName }}
  labels:
    app: postgres
type: Opaque
data:
  POSTGRES_PASSWORD: {{ .Values.postgres.secret.password | b64enc | quote }}
  # Postgres Exporter connection string
  DATA_SOURCE_NAME: {{ printf "postgresql://%s:%s@%s:5432/%s?sslmode=disable" .Values.postgres.user .Values.postgres.secret.password .Values.postgres.host .Values.postgres.database | b64enc | quote }}
